version: '3'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    image: victorcalisto/lsiobase-gui:bionic
    container_name: python
    environment:
      - TZ=Brazil/East
    volumes:
      - ./python:/python
    ports:
      - "8080:3389"
    shm_size: "4gb"