version: '3'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    image: lsiobase/ubuntu:focal
    container_name: python
    environment:
      - PUID=1000 
      - PGID=1000
      - TZ=Brazil/East
    volumes:
      - ./config:/config
    ports:
      - "8080:80"
    shm_size: "4gb"